#!/bin/bash

CURDATE=`date +%Y%m%d`
INDEX=1
FILE=$1
FILE=`echo ${FILE} | sed -e s/'\/$'//`

if [ -z ${FILE} ]; then
        echo "Backup file/directory to file-$CURDATE$INDEX"
        exit 0
fi
if [ ! -z $2 ]; then
        echo "Backup file/directory to file-$CURDATE$INDEX"
        exit 0
fi

INDEX=1
while [ $INDEX -gt 0 ]; do
        if [ ! -e ${FILE}-$CURDATE$INDEX ] ; then
                echo ${FILE}-$CURDATE$INDEX
                cp -a ${FILE} ${FILE}-$CURDATE$INDEX
                INDEX=0
        else
                INDEX=`echo $INDEX+1 | bc`
        fi
done
