#!/bin/bash

CURDATE=`date +%Y%m%d`
INDEX=1

if [ -z $1 ]; then
        echo "Backup file/directory to file-$CURDATE$INDEX"
        exit 0
fi
if [ ! -z $2 ]; then
        echo "Backup file/directory to file-$CURDATE$INDEX"
        exit 0
fi

INDEX=1
while [ $INDEX -gt 0 ]; do
        if [ ! -e $1-$CURDATE$INDEX ] ; then
                echo $1-$CURDATE$INDEX
                cp -a $1 $1-$CURDATE$INDEX
                INDEX=0
        else
                INDEX=`echo $INDEX+1 | bc`
        fi
done
